services:
  ofelia:
    image: mcuadros/ofelia:latest
    command: daemon --docker
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    labels:
      ofelia.enabled: true
      # Attempt #1 - typical WG update time
      ofelia.job-run.upload-assets-1.schedule: 0 10 * * *
      ofelia.job-run.upload-assets-1.container: aftermath-upload-assets
      # Attemt #2 - in case WG delayed an update
      ofelia.job-run.upload-assets-2.schedule: 0 12 * * *
      ofelia.job-run.upload-assets-2.container: aftermath-upload-assets

  upload:
    image: ghcr.io/cufee/aftermath-assets:latest
    build:
      context: .
      dockerfile: Dockerfile
    container_name: aftermath-upload-assets
    env_file:
      - .env
    command: |
      --download \
      --decrypt \
      --parse \
      --app-id '${WARGAMING_APP_ID}' \
      --username '${STEAM_USERNAME}' \
      --password '${STEAM_PASSWORD}' \
      --mail \
      --mail-host '${EMAIL_HOST}' \
      --mail-user '${EMAIL_USER}' \
      --mail-pass '${EMAIL_PASSWORD}' \
      /static-data/downloaded \
      /assets
    volumes:
      - credentials:/downloader/data
      - static:/static-data

volumes:
  credentials:
  static:
