services:
  local:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - ".env"
    command: "app --help"
    environment:
      DOWNLOADER_CMD_PATH: /downloader/DepotDownloader
