services:
  upload:
    image: ghcr.io/cufee/aftermath-assets:latest
    build:
      context: .
      dockerfile: Dockerfile
    container_name: aftermath-upload-assets
    env_file:
      - .env
    command: --download --decrypt --parse --mail /static-data/downloaded /assets
    volumes:
      - ./tmp/credentials:/downloader/data
      - ./tmp/static:/static-data
