name: Upload Assets

on:
  workflow_run:
    workflows: ["Docker Image"]
    types:
      - completed
  schedule:
    - cron: "0 12 * * *"
    - cron: "0 10 * * *"
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/cufee/aftermath-assets:latest
    environment: upload-assets
    env:
      XDG_DATA_HOME: /downloader/data
      DOWNLOADER_CMD_PATH: DepotDownloader
      DOWNLOADER_FILE_LIST: /downloader/filelist.txt
      DECRYPT_DIR_PATH: /static-data/decrypted
      DOWNLOADER_DEPOT_ID: 444202
      DOWNLOADER_APP_ID: 444200
    steps:
      - name: Download downloader data
        id: download-downloader-data
        uses: actions/cache@v4
        with:
          path: /downloader/data
          key: downloader-data
      - name: Generate assets
        shell: bash
        run: |
          app --download --decrypt --parse --mail --password '${{ secrets.DOWNLOADER_STEAM_PASSWORD }}' --username '${{ secrets.DOWNLOADER_STEAM_USERNAME }}' --mail-host '${{ secrets.EMAIL_HOST }}' --mail-pass '${{ secrets.EMAIL_PASSWORD }}' --mail-user '${{ secrets.EMAIL_USER }}' /static-data/downloaded /assets
      - name: "Tar assets"
        run: tar -cvf assets.tar /assets
      - name: Upload assets
        uses: actions/upload-artifact@v4
        with:
          name: assets
          path: assets.tar
      - name: Save downloader data
        id: save-downloader-data
        uses: actions/cache/save@v4
        with:
          path: /downloader/data
          key: downloader-data
  upload:
    needs: generate
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: Download assets
        uses: actions/download-artifact@v4
        with:
          name: assets
          path: /tmp
      - name: Untar assets
        run: tar -xvf /tmp/assets.tar -C ./assets --strip-components=1 --overwrite
      - name: Extract version tag from metadata.json
        uses: sergeysova/jq-action@v2
        id: version
        with:
          cmd: "jq .tag ./assets/metadata.json -r"
      - name: Commit assets to the repository
        uses: stefanzweifel/git-auto-commit-action@v5
        id: commit-changes
        with:
          tagging_message: ${{ steps.version.outputs.value }}
      - name: Zip assets
        run: zip -r /tmp/assets.zip ./assets
      - name: Upload a new release
        # if: steps.commit-changes.outputs.changes_detected == 'true'
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: /tmp/assets.zip
          asset_name: assets.zip
          tag: ${{ steps.version.outputs.value }}
          overwrite: true
          body: "Assets - Automated Release"
